### PR TITLE
first pass putting cumulative txo count in block contents

### PR DESCRIPTION
**Pull request by xoloki**
Soundtrack of this PR: [link to song that really fits the mood of this PR]()

### Motivation

Fix FOG-116

### In this PR
* Add cumulative txo count to BlockContents struct and deal with the fallout

FOG-116

### Future Work
* No future work

### CODE REVIEW

**Comment by eranrund** [comment]
Why is this needed when the `Block` structure already has it?
https://github.com/mobilecoinofficial/mobilecoin/blob/master/transaction/core/src/blockchain/block.rs#L39

**Comment by xoloki** [comment]
> Why is this needed when the `Block` structure already has it?
> https://github.com/mobilecoinofficial/mobilecoin/blob/master/transaction/core/src/blockchain/block.rs#L39

https://mobilecoin.atlassian.net/browse/FOG-116 is about copying this field from the block headers (i.e. Block struct) to the external AP:

**Comment by xoloki** [comment]
I assume that if there was a clean solution @garbageslam would have done so instead of leaving this comment https://github.com/mobilecoinofficial/internal/blob/master/src/fog/ledger/server/src/block_service.rs#L59

**Comment by eranrund** [comment]
I believe the field didn't exist at the time. In this function you can also call `self.ledger.get_block` (https://github.com/mobilecoinofficial/mobilecoin/blob/8f68f6e1314486caaae46dafe08302a07063bf39/ledger/db/src/ledger_trait.rs#L25) and just get the field from there.

**Comment by garbageslam** [comment]
@xoloki i think at the time that I made the proto for ledger server, there was no clean way to do this, and the ticket was to make ledger db able to do it and then make fog use the new ledger db. but i think eran actually made ledger db able to do this cleanly already? I'm not actually sure

the goal of the ticket was, in my mind, to resolve these fixmes:

```
chris@chris-ThinkPad-X1-Carbon-7th:~/mobilecoinofficial/internal$ git grep "FOG-116"
src/fog/api/proto/ledger.proto:    /// FIXME FOG-116: This number is needed but is not returned at present revision
src/fog/ledger/server/src/block_service.rs:        result.global_txo_count = 0; // FIXME: FOG-116
src/fog/ledger/server/tests/connection.rs:        assert_eq!(result.blocks[0].global_txo_count, 0); // FIXME FOG-116
src/fog/ledger/server/tests/connection.rs:        assert_eq!(result.blocks[0].global_txo_count, 0); // FIXME FOG-116
src/fog/ledger/server/tests/connection.rs:        assert_eq!(result.blocks[1].global_txo_count, 0); // FIXME FOG-116
```

**Comment by xoloki** [comment]
Closing in favor of https://github.com/mobilecoinofficial/internal/pull/269

**Pull request closed without merging**
